/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.Color;
import java.net.URL;

import controlador.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andre
 */
public class panel_inicial extends javax.swing.JFrame {
    Controlador controlador;
    int xMouse, yMouse;
    public panel_inicial(Controlador vista){
        controlador=vista;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        LearnProgram = new javax.swing.JButton();
        DeletData = new javax.swing.JButton();
        TurnUpCorrection = new javax.swing.JButton();
        LOGO = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        BtnExit = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        MOON = new javax.swing.JLabel();
        BLUE = new javax.swing.JLabel();
        WHITE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BG.setMinimumSize(new java.awt.Dimension(860, 460));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LearnProgram.setBackground(new java.awt.Color(0, 153, 204));
        LearnProgram.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        LearnProgram.setForeground(new java.awt.Color(255, 255, 255));
        LearnProgram.setText("Entrenar");
        LearnProgram.setToolTipText("");
        LearnProgram.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LearnProgram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LearnProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LearnProgramActionPerformed(evt);
            }
        });
        BG.add(LearnProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 170, 70));

        DeletData.setBackground(new java.awt.Color(0, 153, 204));
        DeletData.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        DeletData.setForeground(new java.awt.Color(255, 255, 255));
        DeletData.setText("Borrar datos");
        DeletData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DeletData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeletData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletDataActionPerformed(evt);
            }
        });
        

        TurnUpCorrection.setBackground(new java.awt.Color(0, 153, 204));
        TurnUpCorrection.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        TurnUpCorrection.setForeground(new java.awt.Color(255, 255, 255));
        TurnUpCorrection.setText("Activar correccion");
        TurnUpCorrection.setToolTipText("");
        TurnUpCorrection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TurnUpCorrection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TurnUpCorrection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurnUpCorrectionActionPerformed(evt);
            }
        });
        BG.add(TurnUpCorrection, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 170, 70));

        LOGO.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        LOGO.setForeground(new java.awt.Color(255, 255, 255));
        LOGO.setText("StartDrift");
        BG.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 290, 60));

        Header.setOpaque(false);
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        BtnExit.setBackground(new java.awt.Color(0, 102, 153));
        BtnExit.setForeground(new java.awt.Color(0, 102, 153));
        URL url1 = panel_inicial.class.getResource("/img/delete.png");
        exit.setIcon(new javax.swing.ImageIcon(url1)); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnExitLayout = new javax.swing.GroupLayout(BtnExit);
        BtnExit.setLayout(BtnExitLayout);
        BtnExitLayout.setHorizontalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit)
        );
        BtnExitLayout.setVerticalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 820, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));
        URL url2 = panel_inicial.class.getResource("/img/final.png");
        MOON.setIcon(new javax.swing.ImageIcon(url2)); // NOI18N
        MOON.setToolTipText("");
        BG.add(MOON, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -130, 400, 410));
        URL url3 = panel_inicial.class.getResource("/img/99.jpg");
        BLUE.setIcon(new javax.swing.ImageIcon(url3)); // NOI18N
        BG.add(BLUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 280));
        URL url4 = panel_inicial.class.getResource("/img/white.jpg");
        WHITE.setIcon(new javax.swing.ImageIcon(url4)); // NOI18N
        BG.add(WHITE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 860, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TurnUpCorrectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurnUpCorrectionActionPerformed
        // TODO add your handling code here:
        controlador.escucharEventos();
    }//GEN-LAST:event_TurnUpCorrectionActionPerformed

    private void DeletDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletDataActionPerformed

    private void LearnProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LearnProgramActionPerformed

        controlador.escucharEventos();
          
    }//GEN-LAST:event_LearnProgramActionPerformed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x - xMouse,y - yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_HeaderMouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        BtnExit.setBackground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        BtnExit.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_exitMouseExited

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel BLUE;
    private javax.swing.JPanel BtnExit;
    public static javax.swing.JButton DeletData;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LOGO;
    public static javax.swing.JButton LearnProgram;
    private javax.swing.JLabel MOON;
    public static javax.swing.JButton TurnUpCorrection;
    private javax.swing.JLabel WHITE;
    private javax.swing.JLabel exit;
    // End of variables declaration//GEN-END:variables
}
